### ISSUE TITLE
Proejct Structure

### ISSUE THREAD

**Issue by omonimus1** [leadthefuture/ML-and-DataScience-preparation#2]
Split content via 2 folders: ML and DataScience

Update Readme by:
* Explaining goal and content of the repo
* Add a link to lead the future for buying me a coffee (must bring to the donate section for LeadTheFuture)

**Comment by omonimus1** [comment]
@francescodisalvo05  Would you be up for the REadme improvements?
Then, we go further with the learning sections :).

**Comment by francescodisalvo05** [comment]
Sure! I'll try to arrange it asap 💪🏻

**Comment by omonimus1** [comment]
@francescodisalvo05 I have fixed the main REadme;
I was thinking, we should created an index following the structrue followed [here](https://github.com/omonimus1/geeks-for-geeks-solutions#Algorithms-and-Data-structures)

So, from the readme (of ML for example), clicking on supervised learning, we should go directly in that section;
Note: Better do not add a title section (and element in the index), if there is no learning material associated to it;

**Comment by francescodisalvo05** [comment]
Great! I got your point, seems good!
